services:
  - type: web
    name: audio-converter
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip3 install -r requirements.txt
      pip3 list
    startCommand: python3 app.py
    plan: free